=== DavydenkoAnton/JWD/Task3/src/main/resources/flowers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Flowers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Flower">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Soil" type="xs:string">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="ground"/>
                                        <xs:enumeration value="send"/>
                                        <xs:enumeration value="water"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Origin" type="xs:string">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="by"/>
                                        <xs:enumeration value="ru"/>
                                        <xs:enumeration value="pl"/>
                                        <xs:enumeration value="de"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Parametres">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="VisualParametres">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="LeafColor" type="xs:string">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="green"/>
                                                                <xs:enumeration value="blue"/>
                                                                <xs:enumeration value="red"/>
                                                                <xs:enumeration value="white"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="Stem" type="xs:string">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="green"/>
                                                                <xs:enumeration value="blue"/>
                                                                <xs:enumeration value="red"/>
                                                                <xs:enumeration value="white"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="Height" type="xs:integer">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="0"/>
                                                                <xs:maxInclusive value="2000"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="InsideParametres">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Weight" type="xs:integer">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="0"/>
                                                                <xs:maxInclusive value="5000"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Temperature" type="xs:integer">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="-20"/>
                                        <xs:maxInclusive value="30"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Photophilous" type="xs:boolean"/>
                            <xs:element name="Watering" type="xs:integer">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="5000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Multiplying" type="xs:string">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="byLeaf"/>
                                        <xs:enumeration value="byStem"/>
                                        <xs:enumeration value="bySeed"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DavydenkoAnton/JWD/Task3/target/classes/greenhouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<Flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="flowers.xsd">
    <Flower>
        <ID>1</ID>
        <Name>rose</Name>
        <Soil>ground</Soil>
        <Origin>ru</Origin>
        <Parametres>
            <VisualParametres>
                <LeafColor>red</LeafColor>
                <Stem>green</Stem>
                <Height>1000</Height>
            </VisualParametres>
            <InsideParametres>
                <Weight>1000</Weight>
            </InsideParametres>
        </Parametres>
        <Temperature>15</Temperature>
        <Photophilous>true</Photophilous>
        <Watering>1000</Watering>
        <Multiplying>bySeed</Multiplying>
    </Flower>
    <Flower>
        <ID>2</ID>
        <Name>melon</Name>
        <Soil>ground</Soil>
        <Origin>ru</Origin>
        <Parametres>
            <VisualParametres>
                <LeafColor>red</LeafColor>
                <Stem>green</Stem>
                <Height>1000</Height>
            </VisualParametres>
            <InsideParametres>
                <Weight>1000</Weight>
            </InsideParametres>
        </Parametres>
        <Temperature>15</Temperature>
        <Photophilous>true</Photophilous>
        <Watering>1000</Watering>
        <Multiplying>bySeed</Multiplying>
    </Flower>
</Flowers>

=== DavydenkoAnton/JWD/Task3/src/main/resources/greenhouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<Flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="flowers.xsd">
    <Flower>
        <ID>1</ID>
        <Name>rose</Name>
        <Soil>water</Soil>
        <Origin>by</Origin>
        <Parametres>
            <VisualParametres>
                <LeafColor>blue</LeafColor>
                <Stem>green</Stem>
                <Height>200</Height>
            </VisualParametres>
            <InsideParametres>
                <Weight>60</Weight>
            </InsideParametres>
        </Parametres>
        <Temperature>18</Temperature>
        <Photophilous>true</Photophilous>
        <Watering>700</Watering>
        <Multiplying>bySeed</Multiplying>
    </Flower>
    <Flower>
        <ID>2</ID>
        <Name>tulip</Name>
        <Soil>ground</Soil>
        <Origin>ru</Origin>
        <Parametres>
            <VisualParametres>
                <LeafColor>red</LeafColor>
                <StemColor>green</StemColor>
                <Height>1000</Height>
            </VisualParametres>
            <InsideParametres>
                <Weight>1000</Weight>
            </InsideParametres>
        </Parametres>
        <Temperature>15</Temperature>
        <Photophilous>true</Photophilous>
        <Watering>1000</Watering>
        <Multiplying>bySeed</Multiplying>
    </Flower>
</Flowers>
